Feature/nns assists
Keith3895/NNS-BOT pull request #35
Opened 2020-09-23 14:06 UTC by ShashankHegde16

## Description
The pull request is to add the assist feature. Below are the changes included.

- Added a suppport for command !nns.assist
- added a method in ``jiraApiHanlder`` service to search for the entered ``description/ticket reference`` followed by !nns.assist.

## Test Cases
- If user just key in the ``!nns.assist`` command, bot will respond with supported format for using the ``!nns.assist``.
- On entering the description of issue/task/story followed by ``!nns.assist command`` , the bot will search for the issues that matches the entered description and responds with all the matched issues. If issue does not exists , bot will ask the user to create one issue using ``!nns.bug`` command.

cooldownService, A service to handle all the functionality of the cooldown feature.
a method and check on bot.ts to check or add cooldown.
a cooldown variable on all/most commands to define cooldown specific to the command. (excluded nns.bug as it has 10s timer already)
additional changes
updated lint config to add more code smell checks.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have added tests to cover my changes.

### Closing features
Closes #31 

## Checklist before raising the PR.
* [x] Have you added an explanation of what your changes are?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Have you updated the documentation accordingly.

2020-09-23 14:49 UTC, Keith3895 requested changes

2020-09-23 14:49 UTC, Keith3895 commented on src/service/jiraApiHandler.ts
> +        return new Promise((resolved, rejected) => {
can you explore if we can make the promise in line 54 into a function. we are writing the same line multiple times.

2020-09-23 14:49 UTC, Keith3895 commented on src/commands/nns-assist.ts
> +                    message.reply('The entered issue does not exists. Do you want to create one? If Yes, Please use !nns.bug command to raise the ticket');
Codacy found an issue: [Exceeds maximum line length of 120](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6224848)

2020-09-23 14:49 UTC, Keith3895 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6224848&bid=20288023)

2020-09-24 17:30 UTC, Keith3895 requested changes
the changes on the jiraAPI handler are not something I want to go ahead with. It breaks the structure of the source code. 

The JiraAPI service has become a utility method. that is not the right way to do it. you should do any/all jira related object mapping in the jiraAPI service.

2020-09-24 17:30 UTC, Keith3895 commented on src/commands/nns-bug.ts
> +                const options = {
set the options and other info on the APIHandler service. don't set it in the command class.

2020-09-24 20:06 UTC, Keith3895 commented on src/service/jiraApiHandler.ts
> +        let searchObj = {
Codacy found an issue: [Identifier 'searchObj' is never reassigned; use 'const' instead of 'let'.](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6224848)

2020-09-24 20:06 UTC, Keith3895 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity decreasing per file
==============================
+ src/service/utils.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6224848&bid=20288023)

2020-09-24 20:09 UTC, Keith3895 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/service/utils.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6224848&bid=20288023)

2020-09-24 20:14 UTC, Keith3895 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/service/utils.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6224848&bid=20288023)

2020-09-25 04:44 UTC, Keith3895 approved these changes

2020-09-25 05:08 UTC, ramesh-bg approved these changes

2020-09-25 08:55 UTC, merged