Feature/nns feature
Keith3895/NNS-BOT pull request #36
Opened 2020-09-25 13:18 UTC by ramesh-bg

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have added tests to cover my changes.

### Closing features
Closes #15

## Checklist before raising the PR.
* [x] Have you added an explanation of what your changes are?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Have you updated the documentation accordingly.

Test Cases

- Added a new command !nns.feature
- Send a message with the above command to initiate !nns.feature flow
- Bot will respond with set of queries like Title and Description.
- Reply with all the queries and respond with yes for confirmation query.
- On success , bot will respond with feature message embed.
- If replied No for confirmation , then feature creation gets cancelled and bot replies with respective message.
`Note: All the feature queries has an timeout duration of 2 mins`

2020-09-25 13:19 UTC, Keith3895 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/service/cooldownService.ts  2
         

Complexity decreasing per file
==============================
+ src/service/utils.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6237539&bid=20322214)

2020-09-25 13:44 UTC, ShashankHegde16 requested changes
Please raise it to dev

2020-09-25 15:07 UTC, Keith3895 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/service/cooldownService.ts  2
         

Complexity decreasing per file
==============================
+ src/service/utils.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6237539&bid=20322214)

2020-09-25 15:07 UTC, Keith3895 commented on src/service/jiraApiHandler.ts
> +                                'text': 'sample Description',
Codacy found an issue: [Identifier 'reqObj' is never reassigned; use 'const' instead of 'let'.](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6237539)

2020-09-25 15:17 UTC, Keith3895 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6237539&bid=20322214)

2020-09-25 15:17 UTC, Keith3895 commented on src/service/jiraApiHandler.ts
> +        let reqObj = Object.assign({}, this.issueObj);
Codacy found an issue: [Identifier 'reqObj' is never reassigned; use 'const' instead of 'let'.](https://app.codacy.com/manual/keith30895/NNS-BOT/pullRequest?prid=6237539)

2020-09-25 15:18 UTC, ramesh-bg commented on src/service/jiraApiHandler.ts
> +        let reqObj = Object.assign({}, this.issueObj);
Value is reassigned

2020-09-25 15:27 UTC, ramesh-bg commented
> Please raise it to dev

Done

2020-09-25 15:34 UTC, ShashankHegde16 requested changes
Please update milestone,project,label

2020-09-25 15:34 UTC, ShashankHegde16 commented on src/service/jiraApiHandler.ts
> +    private issueObj = {
Do we need this variable?

2020-09-26 03:17 UTC, ramesh-bg commented on src/service/jiraApiHandler.ts
> +    private issueObj = {
removed the variable

2020-09-27 06:27 UTC, Keith3895 approved these changes

2020-09-27 06:27 UTC, Keith3895 commented on tests/commands/nns-feature.spec.ts
> +        mockedMessageInstance.content = 'Date picker';
@ShashankHegde16 do you think the issue that we got created on jira came from here?

2020-09-27 08:29 UTC, ShashankHegde16 commented on tests/commands/nns-feature.spec.ts
> +        mockedMessageInstance.content = 'Date picker';
Nope because in issue Picker is in caps

2020-09-27 08:30 UTC, ShashankHegde16 approved these changes

2020-09-28 09:40 UTC, merged